insert into customer (id, name, lastname, email, created_at) values (1, 'Willy', 'Fernandez', 'willy@gmail.com', '2019-09-07');
insert into customer (id, name, lastname, email, created_at) values (2, 'Agustina', 'Fernandez Girones', 'agus@gmail.com', '2019-09-06');
insert into customer (id, name, lastname, email, created_at) values (3, 'Joaquin', 'Fernandez Girones', 'joacko@gmail.com', '2019-09-05');
insert into customer (id, name, lastname, email, created_at) values (4, 'Karina', 'Girones', 'kari@gmail.com', '2019-09-04');
INSERT INTO customer (id, name, lastname, email, created_at) VALUES(5, 'Andres', 'Guzman', 'profesor@bolsadeideas.com', '2017-08-01');
INSERT INTO customer (id, name, lastname, email, created_at) VALUES(6, 'John', 'Doe', 'john.doe@gmail.com', '2017-08-02');
INSERT INTO customer (id, name, lastname, email, created_at) VALUES(7, 'Linus', 'Torvalds', 'linus.torvalds@gmail.com', '2017-08-03');
INSERT INTO customer (id, name, lastname, email, created_at) VALUES(8, 'Jane', 'Doe', 'jane.doe@gmail.com', '2017-08-04');
INSERT INTO customer (id, name, lastname, email, created_at) VALUES(9, 'Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', '2017-08-05');
INSERT INTO customer (id, name, lastname, email, created_at) VALUES(10, 'Erich', 'Gamma', 'erich.gamma@gmail.com', '2017-08-06');
INSERT INTO customer (id, name, lastname, email, created_at) VALUES(11, 'Richard', 'Helm', 'richard.helm@gmail.com', '2017-08-07');
INSERT INTO customer (id, name, lastname, email, created_at) VALUES(12, 'Ralph', 'Johnson', 'ralph.johnson@gmail.com', '2017-08-08');
INSERT INTO customer (id, name, lastname, email, created_at) VALUES(13,'John', 'Vlissides', 'john.vlissides@gmail.com', '2017-08-09');
INSERT INTO customer (id, name, lastname, email, created_at) VALUES(14, 'James', 'Gosling', 'james.gosling@gmail.com', '2017-08-010');
INSERT INTO customer (id, name, lastname, email, created_at) VALUES(15, 'Bruce', 'Lee', 'bruce.lee@gmail.com', '2017-08-11');
INSERT INTO customer (id, name, lastname, email, created_at) VALUES(16, 'Johnny', 'Doe', 'johnny.doe@gmail.com', '2017-08-12');
INSERT INTO customer (id, name, lastname, email, created_at) VALUES(17, 'John', 'Roe', 'john.roe@gmail.com', '2017-08-13');
INSERT INTO customer (id, name, lastname, email, created_at) VALUES(18, 'Jane', 'Roe', 'jane.roe@gmail.com', '2017-08-14');
INSERT INTO customer (id, name, lastname, email, created_at) VALUES(19, 'Richard', 'Doe', 'richard.doe@gmail.com', '2017-08-15');
INSERT INTO customer (id, name, lastname, email, created_at) VALUES(20, 'Janie', 'Doe', 'janie.doe@gmail.com', '2017-08-16');
INSERT INTO customer (id, name, lastname, email, created_at) VALUES(21, 'Phillip', 'Webb', 'phillip.webb@gmail.com', '2017-08-17');
INSERT INTO customer (id, name, lastname, email, created_at) VALUES(22, 'Stephane', 'Nicoll', 'stephane.nicoll@gmail.com', '2017-08-18');
INSERT INTO customer (id, name, lastname, email, created_at) VALUES(23, 'Sam', 'Brannen', 'sam.brannen@gmail.com', '2017-08-19');  
INSERT INTO customer (id, name, lastname, email, created_at) VALUES(24, 'Juergen', 'Hoeller', 'juergen.Hoeller@gmail.com', '2017-08-20'); 
INSERT INTO customer (id, name, lastname, email, created_at) VALUES(25, 'Janie', 'Roe', 'janie.roe@gmail.com', '2017-08-21');
INSERT INTO customer (id, name, lastname, email, created_at) VALUES(26, 'John', 'Smith', 'john.smith@gmail.com', '2017-08-22');
INSERT INTO customer (id, name, lastname, email, created_at) VALUES(27, 'Joe', 'Bloggs', 'joe.bloggs@gmail.com', '2017-08-23');
INSERT INTO customer (id, name, lastname, email, created_at) VALUES(28, 'John', 'Stiles', 'john.stiles@gmail.com', '2017-08-24');
INSERT INTO customer (id, name, lastname, email, created_at) VALUES(29, 'Richard', 'Roe', 'stiles.roe@gmail.com', '2017-08-25');
